/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CignoAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CignoService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CignoVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}